baseURL = 'https://Sahill17.github.io'
languageCode = 'en-us'
title = 'Operations Guy'

pagination.pagerSize = 5

[params]
    description = "Welcome to OG blog"
    dateFormat = "Jan 2, 2006"

[taxonomies]
    tag = "tags"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
